version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  create_tables:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    container_name: create_tables
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
